import { Montserrat } from "next/font/google";
import { FloatingNavbar } from "./components/floatingNav";

import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});


export const metadata = {
  title: "Goadvert | Buy, Sell or Rent",
  description: "Generated by create next app",
};

/**
 * The root layout of the app, which renders the HTML structure, including a
 * `<body>` that contains the children (i.e. the current route) and a
 * `<FloatingNavbar />` component.
 *
 * @param {{ children: React.ReactNode }} props The component props.
 * @returns {JSX.Element} The root layout.
 */
export default function RootLayout(props) {
  const { children } = props;
  return (

      <html lang="en">
        <body>
          {children}
          
        </body>
      </html>
  );
}

