// "use client"
import { Montserrat } from "next/font/google";
import { FloatingNavbar } from "./components/floatingNav";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const publishableKey = process.env.NEXT_PUBLIC_YOUR_KEY_NAME;

export const metadata = {
  title: "Goadvert | Buy, Sell or Rent",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  const { children } = props;
  return (
    <ClerkProvider publishableKey={publishableKey}>
      <html lang="en">
        <body>
          {children}
          <FloatingNavbar />
        </body>
      </html>
    </ClerkProvider>
  );
}

